application: grocshare-0408
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: verify.app

libraries:
- name: MySQLdb
  version: "latest"

- name: jinja2
  version: "latest"

- name: ssl
  version: latest
